# Generated by Django 3.2.3 on 2021-05-29 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210529_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ManyToManyField(to='store.Group'),
        ),
    ]
