# Generated by Django 4.0.4 on 2022-04-23 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_vitonuploads_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_code', models.CharField(max_length=10)),
                ('items', models.ManyToManyField(to='store.product')),
                ('members', models.ManyToManyField(to='store.customer')),
            ],
        ),
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('groupdesc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.groupcart')),
            ],
        ),
    ]
