# Generated by Django 4.0.4 on 2022-04-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_groupcart_grouporder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcart',
            name='members',
        ),
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.ManyToManyField(to='store.groupcart'),
        ),
    ]
